=== order12a/InfopulseJavaSecond/lection17/TaxesTemplate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.com/MobileTaxes"
        xmlns:tns="http://www.example.com/MobileTaxes">
    <element name="tax_list" type="tns:tax_list"/>
    <complexType name="tax_list">
        <sequence>
            <element type="tns:name" name="name" maxOccurs="unbounded" minOccurs="0"/>
        </sequence>
    </complexType>
    <complexType name="name">
       <sequence>
           <element name="operator_name" type="string"/>
           <element name="payroll" type="double" maxOccurs="1" minOccurs="1"/>
           <element name="call_price" type="tns:call_prices" maxOccurs="1" minOccurs="1"/>
           <element name="sms_price" type="double" maxOccurs="1" minOccurs="1"/>
           <element name="params" type="tns:params"/>
       </sequence>
    </complexType>

    <complexType name="call_prices">
        <sequence>
            <element name="in_network" type="double" maxOccurs="1" minOccurs="1"/>
            <element name="out_network" type="double" maxOccurs="1" minOccurs="1"/>
            <element name="office_stations" type="double" maxOccurs="1" minOccurs="1"/>
        </sequence>
    </complexType>
    <complexType name="params">
        <sequence>
            <element name="number" type="double" maxOccurs="1" minOccurs="1"/>
            <element name="taxification" type="string" maxOccurs="1" minOccurs="0"/>
            <element name="conn_tax" type="double" maxOccurs="1" minOccurs="1"/>
        </sequence>
    </complexType>
    <simpleType name="taxification">
        <restriction base="string">
            <pattern value="12sec|minute" />
        </restriction>
    </simpleType>
</schema>

=== order12a/InfopulseJavaSecond/lection17/MobileTaxes.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:tax_list xmlns:tns="http://www.example.com/MobileTaxes"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.example.com/MobileTaxes  TaxesTemplate.xsd">
    <name>
        <operator_name>Life</operator_name>
        <payroll>12</payroll>
        <call_price>
            <in_network>0</in_network>
            <out_network>0.3</out_network>
            <office_stations>0.6</office_stations>
        </call_price>
        <sms_price>0.4</sms_price>
        <params>
            <number>0639395945</number>
            <taxification>minute</taxification>
            <conn_tax>0</conn_tax>
        </params>
    </name>
    <name>
        <operator_name>Kuchmastar</operator_name>
        <payroll>15</payroll>
        <call_price>
            <in_network>0</in_network>
            <out_network>0.4</out_network>
            <office_stations>0.55</office_stations>
        </call_price>
        <sms_price>0.6</sms_price>
        <params>
            <number>0674515945</number>
            <taxification>12sec</taxification>
            <conn_tax>0.3</conn_tax>
        </params>
    </name>
    <name>
        <operator_name>Vatafone</operator_name>
        <payroll>30</payroll>
        <call_price>
            <in_network>0.1</in_network>
            <out_network>0.5</out_network>
            <office_stations>0.8</office_stations>
        </call_price>
        <sms_price>0.5</sms_price>
        <params>
            <number>0939395945</number>
            <taxification>12sec</taxification>
            <conn_tax>0.4</conn_tax>
        </params>
    </name>
</tns:tax_list>
